Allow setting `model_name` in the prompt's TOML
talkdai/dialog pull request #51
Opened 2023-11-23 15:34 UTC by cosmastech

To resolve https://github.com/talkdai/dialog/issues/31

2023-11-23 16:59 UTC, avelino requested changes

2023-11-23 16:59 UTC, avelino commented on src/llm/__init__.py
> +MODEL_NAME = PROMPT.get("model_name", default="gpt-3.5-turbo")
this configuration should be in the settings package

https://github.com/talkdai/dialog/blob/main/src/settings.py

2023-11-23 18:45 UTC, vmesel requested changes

2023-11-23 18:45 UTC, vmesel commented on src/settings.py
> +MODEL_NAME = PROMPT.get("model_name", default="gpt-3.5-turbo")
```
api-web-1  |     MODEL_NAME = PROMPT.get("model_name", default="gpt-3.5-turbo")
api-web-1  |                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
api-web-1  | TypeError: dict.get() takes no keyword arguments
```

Can you please fix this?

2023-11-24 13:39 UTC, cosmastech commented on src/settings.py
> +MODEL_NAME = PROMPT.get("model_name", default="gpt-3.5-turbo")
Thanks!

2023-11-24 13:43 UTC, vmesel approved these changes

2023-11-24 13:44 UTC, vmesel commented
LGTM! @avelino what are your thoughts?

2023-11-24 16:38 UTC, avelino approved these changes

2023-11-24 17:00 UTC, lgabs commented
Later we can maybe put parameters and configs related to the llm configuration into the same `LLM_CONFIG`, which [entered today](https://github.com/talkdai/dialog/pull/59), actually. This will be specially useful when we think about using different llms.

Besides that, it'd be good to indicate about the model_name in the [README](https://github.com/talkdai/dialog#toml-prompt-configuration).

2023-11-24 20:37 UTC, vmesel commented
@cosmastech can you resolve the conflicts?

2023-11-24 20:59 UTC, cosmastech commented
> @cosmastech can you resolve the conflicts?

Should be all resolved @vmesel

2023-11-24 21:26 UTC, merged

2023-11-24 21:27 UTC, avelino commented
thanks @cosmastech